"""The snapshot parser and writers, against the JS implementation they replace.

tests/fixtures/*.json were generated by running the front end's
src/lib/handBody.js — the code that prepared the hand before this coordinator
existed — over the mock host's snapshots, a seeded fakebot corpus and a set of
edge cases. The front end renders what this module returns, so "the same output
as the JS" is the specification, not an approximation of it.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from zigsolver_coordinator import hand_body as hb

FIXTURES = Path(__file__).parent / "fixtures"
PARSE = json.loads((FIXTURES / "hand_body_parse.json").read_text())
WRITERS = json.loads((FIXTURES / "hand_body_writers.json").read_text())


def mismatch(expected, got, path="$"):
    """The first path where two JSON values differ, or None.

    Numbers compare by value (JS has no int/float split, so `25` and `25.0` are
    the same number), but a boolean is never a number.
    """
    if isinstance(expected, bool) or isinstance(got, bool):
        return None if expected is got else f"{path}: {expected!r} != {got!r}"
    if isinstance(expected, (int, float)) and isinstance(got, (int, float)):
        return None if expected == got else f"{path}: {expected!r} != {got!r}"
    if isinstance(expected, dict) and isinstance(got, dict):
        if set(expected) != set(got):
            return f"{path}: keys {sorted(set(expected) ^ set(got))} differ"
        for k in expected:
            found = mismatch(expected[k], got[k], f"{path}.{k}")
            if found:
                return found
        return None
    if isinstance(expected, list) and isinstance(got, list):
        if len(expected) != len(got):
            return f"{path}: length {len(expected)} != {len(got)}"
        for i, (e, g) in enumerate(zip(expected, got)):
            found = mismatch(e, g, f"{path}[{i}]")
            if found:
                return found
        return None
    return None if expected == got else f"{path}: {expected!r} != {got!r}"


def roundtrip(value):
    """What the wire would carry — the fixture is JSON, so compare JSON to JSON."""
    return json.loads(json.dumps(value))


@pytest.mark.parametrize("case", PARSE, ids=[c["name"] for c in PARSE])
def test_parse_matches_js(case):
    got = roundtrip(hb.parse_hand_body(case["body"]))
    assert mismatch(case["expected"], got) is None


@pytest.mark.parametrize("case", PARSE, ids=[c["name"] for c in PARSE])
def test_decision_key_matches_js(case):
    assert hb.decision_key(hb.parse_hand_body(case["body"])) == case["decisionKey"]


def test_corpus_covers_what_it_should():
    """The fixture is only a guard if it exercises the interesting shapes."""
    parsed = [c["expected"] for c in PARSE if c["expected"]]
    assert any(p["finished"] for p in parsed)
    assert any(p["street"] == 3 for p in parsed)
    assert any(p["tableSize"] >= 9 for p in parsed)
    assert any(p["tableSize"] == 2 for p in parsed)
    assert any(p["warnings"] for p in parsed)
    assert any(s["allIn"] for p in parsed for s in p["seats"])


@pytest.mark.parametrize("case", WRITERS["writeStats"], ids=[c["name"] for c in WRITERS["writeStats"]])
def test_write_stats_matches_js(case):
    assert hb.write_stats(case["body"], case["byName"]) == case["expected"]


@pytest.mark.parametrize(
    "case", WRITERS["writeTournament"], ids=[c["name"] for c in WRITERS["writeTournament"]]
)
def test_write_tournament_matches_js(case):
    assert hb.write_tournament(case["body"], case["values"]) == case["expected"]


def test_formatting_matches_js():
    f = WRITERS["formatting"]
    for c in f["statLine"]:
        assert hb.stat_line(c["key"], c["value"]) == c["expected"], c
    for c in f["tournamentPhrase"]:
        assert hb.tournament_phrase(c["key"], c["value"]) == c["expected"], c
    for c in f["tournamentHeaderLine"]:
        assert hb.tournament_header_line(c["values"]) == c["expected"], c


def test_written_stats_are_read_back():
    """One body downstream: what is written is what the parser then sees."""
    body = next(c["body"] for c in PARSE if c["name"] == "mock-SNAPSHOT")
    written = hb.write_stats(body, {"Sasha M": {"VPIP": 41, "ATS": 12.5}})
    sasha = next(s for s in hb.parse_hand_body(written)["seats"] if s["name"] == "Sasha M")
    assert sasha["stats"] == {"VPIP": 41, "ATS": 12.5}


def test_log_lines_are_not_bodies():
    assert hb.parse_hand_body("Hood: reading stats") is None
    assert hb.parse_hand_body("") is None
    assert hb.parse_hand_body(None) is None
    assert hb.is_hand_over_line("Hand finished")
    assert not hb.is_hand_over_line("Hand #4711")
